version: '3'
services:
  seed:
    container_name: seed
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - env/defaults.env
    ports:
      - '3001:3001'

networks:
  default:
    name: SEED_NETWORK
